name: Codacy PR Analysis
on:
  pull_request:

jobs:
  analyze-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter / Dart
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x.x"

      - name: Install project dependencies
        run: flutter pub get

      - name: Install Codacy CLI v2
        run: |
          bash -c "$(curl -Ls https://raw.githubusercontent.com/codacy/codacy-cli-v2/main/codacy-cli.sh)"
          chmod +x codacy-cli && sudo mv codacy-cli /usr/local/bin/

      - name: Bootstrap Codacy CLI (if needed)
        run: |
          if [ -f .codacy/codacy.yaml ]; then
            echo "Codacy config exists – skip init"
          else
            codacy-cli init
          fi

      - name: (Optional) Discover tools
        run: codacy-cli config discover .

      - name: Install configured tools
        run: codacy-cli install

      - name: Analyze and generate SARIF
        run: codacy-cli analyze --format sarif --output analysis.sarif

      - name: Upload SARIF to Codacy
        run: |
          codacy-cli upload \
            --sarif-path analysis.sarif \
            --commit-uuid "${{ github.event.pull_request.head.sha }}" \
            --project-token "${{ secrets.CODACY_PROJECT_TOKEN }}"

